# -*- coding: utf-8 -*-
"""Miniproject_studentprogresstracking_DIWAKAR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RLCahKrdYTTg8fqgs6iEsdjUki1FbyV7

# Welcome to Colab!
"""

print("--------------------------------------------------")
print("   ******STUDENT PROGRESS TRACKING SYSTEM******    ")
print("--------------------------------------------------")
name=input("STUDENT NAME     :")
c=   input("STUDENT CLASS    :")
r=   input("STUDENT ROLL NO  :")
print("---------------------------------------------")
sub=int(input("Enter no of subjects :"))
n=sub
marks=[]
print("---------------------------------------------")
for i in range(0,n):
    mark=int(input(f"Enter your subject {i+1} marks :"))
    marks.append(mark)
    if mark<=34:
        print(f"The student {name} is fail {i+1}")
#print(f"Marks {Marks}")
print("---------------------------------------------")
print(f"The student {name} Marks as follows:")
total=0
for i in range(0,n):
    total=marks[i]+total
print(f"The Total Marks  :{total} ")
Average=0
Average=total/n
print(f"The Average Marks :{Average}")
print("---------------------------------------------")
#print("Grade")
if Average>90:
    Grade="A"
elif Average>75:
    Grade="B"
elif Average>50:
    Grade="C"
elif Average>40:
    Grade="D"
elif Average<=34:
    print("You are failed")
else:
    print(f"You are pass ")
print(f"Grade {Grade}")
if any (mark<35 for mark in marks):
    Status = "FAIL"
else:
    Status = "Pass"
print(f"The Status : {Status}")
print("---------------------------------------------")
print("***** STUDENT PROGRESS REPORT *****")
print("---------------------------------------------")
print(f"STUDENT NAME    :{name}")
print(f"STUDENT CLASS   :{c}")
print(f"STUDENT ROLL NO :{r}")
print(f"STUDENT AVERAGE :{Average}")
print(f"STUDENT GRADE   :{Grade}")
print(f"STUDENT RESULT  :{Status}")
print("---------------------------------------------")
print("---------------------------------------------")
print("             ***Menu system***                ")
print("---------------------------------------------")
print(" What Do You Want Next ?")
print("---------------------------------------------")
Choice=input("Enter your choice :")
while Choice!="4":
    if Choice=="1":
        print(f"The Total Marks: {total}")
        Choice=input("Enter your choice :")
        print("---------------------------------------------")
    elif Choice=="2":
        print(f"The Student Average: {Average}")
        Choice=input("Enter your choice :")
        print("---------------------------------------------")
    elif Choice=="3":
        print("***** STUDENT PROGRESS REPORT *****")
        print("---------------------------------------------")
        print(f"STUDENT NAME    :{name}")
        print(f"STUDENT CLASS   :{c}")
        print(f"STUDENT ROLL NO :{r}")
        print(f"STUDENT AVERAGE :{Average}")
        print(f"STUDENT GRADE   :{Grade}")
        print(f"STUDENT RESULT  :{Status}")
        Choice=input("Enter your choice :")
        print("---------------------------------------------")
    elif Choice=="4":
        exit
print(" _THANK YOU__ ")
print("---------------------------------------------")